# fly.toml app configuration file generated for zola-ai on 2026-03-09T22:08:58Z

app = 'zola-ai'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  path = "/"
  interval = "30s"
  timeout = "5s"
  grace_period = "15s"

[mounts]
  source = "zola_data"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1